// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Tb2PXS1Q8PDIF3uIGDKzYJ81X5stzy4',
    appId: '1:215322214350:web:8de433bc6f0bc763cd759f',
    messagingSenderId: '215322214350',
    projectId: 'sayyan-6b02b',
    authDomain: 'sayyan-6b02b.firebaseapp.com',
    storageBucket: 'sayyan-6b02b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlNYd2SUlKek986m03bsBzV04Hh6rSHYo',
    appId: '1:215322214350:android:22c0dbf3b4a0024bcd759f',
    messagingSenderId: '215322214350',
    projectId: 'sayyan-6b02b',
    storageBucket: 'sayyan-6b02b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANvY-It8uiLfhZ-hrphcxHxIARntldo6A',
    appId: '1:215322214350:ios:ed118c927f53e77acd759f',
    messagingSenderId: '215322214350',
    projectId: 'sayyan-6b02b',
    storageBucket: 'sayyan-6b02b.firebasestorage.app',
    iosBundleId: 'com.example.sayyan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANvY-It8uiLfhZ-hrphcxHxIARntldo6A',
    appId: '1:215322214350:ios:ed118c927f53e77acd759f',
    messagingSenderId: '215322214350',
    projectId: 'sayyan-6b02b',
    storageBucket: 'sayyan-6b02b.firebasestorage.app',
    iosBundleId: 'com.example.sayyan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_Tb2PXS1Q8PDIF3uIGDKzYJ81X5stzy4',
    appId: '1:215322214350:web:1bda40be9b61378dcd759f',
    messagingSenderId: '215322214350',
    projectId: 'sayyan-6b02b',
    authDomain: 'sayyan-6b02b.firebaseapp.com',
    storageBucket: 'sayyan-6b02b.firebasestorage.app',
  );
}
